### ISSUE TITLE
My own after_add overrides the default one

### ISSUE THREAD

**Issue by vpratfr** [Rhyzz/repeatable-fields#10]
If I specify my own after_add function in order to trigger some events, the defaut function is ignored.

This is problematic because the default function is responsible for replacement of the {{row-count-placeholder}} and this is not done anymore.

**Comment by naifamoodi** [comment]
Hi there,

This issue has been addressed over here: https://github.com/Rhyzz/repeatable-fields/issues/9

I'll be taking care of this issue in the next release. So for now use the modified code I have provided in the link above.

Let me know if you have any issues with it.

Regards.

**Comment by naifamoodi** [comment]
Hi,

I have taken care of this using a different method and have committed the new release. Your custom after_add function should accept three arguments now viz. container, new_row and default_after_add. The default after add function is passed to the third argument i.e. to default_after_add which you need to call from your custom function. Example:

```
after_add: function(container, new_row, default_after_add) {
// Your custom code goes here...

default_after_add(container, new_row);
}
```

Regards.
