### ISSUE TITLE
bower ENOTFOUND for various jquery-ui deps

### ISSUE THREAD

**Issue by SkyLeach** [Rhyzz/repeatable-fields#14]
`bower ui.mouse#>=1.10.3      ENOTFOUND Package ui.mouse not found`

but sometimes it gives

`bower ui.core#>=1.10.3       ENOTFOUND Package ui.core not found`

and sometimes

`bower ui.core#>=1.10.3       ENOTFOUND Package ui.widget not found`

I manually installed jquery-ui but still having this problem.

**Comment by SkyLeach** [comment]
actually I think I finally found it...

in `repeatable-fields.jquery.json`

```
{
	"name": "repeatable-fields",
	"version": "1.4.1",
	"title": "Repeatable Fields",
	"author": {
		"name": "Rhyzz",
		"url": "http://www.rhyzz.com"
	},
	"licenses": [
		{
			"type": "MIT",
			"url": "http://opensource.org/licenses/MIT"
		}
	],
	"dependencies": {
		"jquery": ">=1.9.0",
		"jquery-ui": ">=1.10.3"
	},
	"description": "Repeatable Fields is a jQuery plugin which let's you create a set of fields that can be made to repeat.",
	"keywords": [
		"repeatable-fields",
		"dynamic-fields",
		"dynamic-rows",
		"add-remove-rows"
	],
	"homepage": "http://www.rhyzz.com/repeatable-fields.html",
	"docs": "https://github.com/Rhyzz/repeatable-fields",
	"demo": "http://www.rhyzz.com/repeatable-fields.html",
	"download": "http://www.rhyzz.com/repeatable-fields.html",
	"bugs": "https://github.com/Rhyzz/repeatable-fields/issues"
}
```

notice I replaced the ui.<whatev> deps with jquery-ui

**Comment by naifamoodi** [comment]
Hi SkyLeach,

I've just finished taken care of this issue and also tested it and was able to install the package successfully using bower.

Regards.
