### ISSUE TITLE
When using the after_add event, row-count-placeholder is not replaced with actual value

### ISSUE THREAD

**Issue by lokesh7186** [Rhyzz/repeatable-fields#16]
When using the after_add event, row-count-placeholder is not replaced with actual value. I had to copy the plugin's after_add function's code and placed it at the end of my callback function to make it work.

**Comment by naifamoodi** [comment]
Hi. You don't need to copy the function. Just refer to this to see how to call the default function from your custom function: https://github.com/Rhyzz/repeatable-fields/issues/10

**Comment by lokesh7186** [comment]
Thanks
