### ISSUE TITLE
Need more documentation

### ISSUE THREAD

**Issue by speck1990** [Rhyzz/repeatable-fields#17]
Your plugin looks like exactly what I'm needing. The problem is its very hard to find out how to implement it. I went to your website and looked at all the options, but there was no example code. Am I missing where the documentation is?

**Comment by naifamoodi** [comment]
Hi speck,

The documentation is located here: https://github.com/Rhyzz/repeatable-fields

It has an example for the HTML structure and also an example of the Javascript that's required. It also provides a list of configurable options.

A demo is available here: http://www.rhyzz.com/repeatable-fields/index.html

**Comment by speck1990** [comment]
Thanks for the quick reply. I'm new to jquery. I saw that documentation but there weren't code samples of the different examples you provided. So the way i show one row by default is by just duplicating the template portion. So I will have the following:
`<div class="template row">[form fields]</div>
<div class="row">[form fields]</div>`

If that's right, then cool, but just seemed weird to have to duplicate the data.

**Comment by naifamoodi** [comment]
Hi,

The first div in your example i.e.

`<div class="template row">[form fields]</div>`

is the template that's used to generate rows like these:

`<div class="row">[form fields]</div>`

You only need to add a `<div class="row">[form fields]</div>` if there is going to be one row by default when you load the page. Or else if you don't want any rows by default then you'll only have the template.

Let me know if anything is not clear.
