### ISSUE TITLE
Index Issue

### ISSUE THREAD

**Issue by spyropress** [Rhyzz/repeatable-fields#18]
Hi,

First of all great plugin. I want to know how to deal with the index issue i.e

I add two rows the counter is on 2 now then I remove 1 and add other two the index will be

title[0]
title[2]
title[3]

I want it in proper order how to achieve this..

Thanks in advance

**Comment by naifamoodi** [comment]
Hi spyropress,

I am afraid that's currently not possible.

Can I please know why you want the index association to be ordered?

**Comment by spyropress** [comment]
Hi,

So I don't have to parse through all the fields to get to the repeatable field and sort the index if it can be  don't on the client side that would be great.

Thanks

**Comment by spyropress** [comment]
Hi @naifamoodi ,

I think I got the solution how to do the indexing thing. Why place the number within name field

Currently: e.g price[0], price[1]

Why not simply use the array notation and price[] and PHP automatically assign the index which is always in order we left.

Thanks

**Comment by naifamoodi** [comment]
That could work I guess. Give it a shot and let me know how it works. You won't need to modify the plugin for this. Just don't use the {{row-count-placeholder}} placeholder anywhere in your HTML code.

**Comment by naifamoodi** [comment]
This won't work for multidimensional arrays though. You can't have variables like person[][name], person[][age]. You can instead have person[name][], person[age][] however doing it like this will group them in different arrays.
