### ISSUE TITLE
Using repeatable-fields and wp_enqueue_script for Wordpress

### ISSUE THREAD

**Issue by arpan-ghosh** [Rhyzz/repeatable-fields#23]
I'm having a difficult time with using this script in Wordpress.  I've placed the following snippet in functions.php and I have my jquery and jquery ui scripts enqueued before the repeatable script. Is there a specific place I need to put the following:

 `jQuery(function() {
	jQuery('.repeat').each(function() {
		jQuery(this).repeatable_fields();
	});
});`  

This is what I have in functions.php:

` wp_enqueue_script( 'jquery', 'https://code.jquery.com/jquery-1.11.2.min.js', array(), '20120206', true );
    wp_enqueue_script( 'jquery-ui', 'https://code.jquery.com/ui/1.11.4/jquery-ui.min.js', array(), '20120206', true );
    wp_enqueue_script( 'lodash', 'https://cdnjs.cloudflare.com/ajax/libs/lodash.js/3.7.0/lodash.min.js', array(), '20120206', true );
    wp_enqueue_script( 'validate', 'https://cdnjs.cloudflare.com/ajax/libs/jquery-form-validator/2.2.1/jquery.form-validator.min.js', array(), '20120206', true );
    wp_enqueue_script( 'angular', 'https://ajax.googleapis.com/ajax/libs/angularjs/1.3.15/angular.min.js', array(), '20150601', true );
    wp_enqueue_script( 'angular-lodash', get_template_directory_uri() . '/assets/js/vendor/ng-lodash.min.js', array(), '20150601', true );
    wp_enqueue_script( 'angular-checklist-model', get_template_directory_uri() . '/assets/js/vendor/checklist-model.js', array(), '20150601', true );
    wp_enqueue_script( 'jquery-repeatable',  get_template_directory_uri() . '/js/repeatable.js', array(), '20120206', true );
    wp_enqueue_script( 'mede-typeahead',  get_template_directory_uri() . '/app/assets/js/typeahead.js', array(), '20120206', true ); // bootstrap + steve
    wp_enqueue_script( 'mede-maxlength',  get_template_directory_uri() . '/app/assets/js/maxlength.js', array(), '20120206', true ); // bootstrap + steve
	    wp_enqueue_script( 'mede-main',  get_template_directory_uri() . '/app/assets/js/main.js', array(), '20120206', true ); // bootstrap + steve
    wp_enqueue_script( 'mede-navigation', get_template_directory_uri() . '/js/navigation.js', array(), '20120206', true );
    wp_enqueue_script( 'mede-silk-main', get_template_directory_uri() . '/assets/js/build/main.js', array(), '20120206', true ); // SILK main
    wp_enqueue_script( 'mede-silkcheckboxes', get_template_directory_uri() . '/assets/js/vendor/silkcheckbox.js', array(), '20120206', true );
    wp_enqueue_script( 'mede-site', get_template_directory_uri() . '/assets/js/build/site.js', array(), '20120206', true ); // site scripts
    wp_enqueue_script( 'app', get_template_directory_uri() . '/assets/js/app.js', array(), '20120206', true ); // site scripts
	wp_enqueue_script( 'fancybox', get_bloginfo( 'stylesheet_directory' ) . '/js/fancybox/jquery.fancybox.js', array( 'jquery' ), '1.0.0', true);`

Any help would be appreciated! Thanks!

**Comment by naifamoodi** [comment]
There is no specific place that you need to place it in. You can place inline or in any script that's loaded after repeatable.js

________________________________
