### ISSUE TITLE
Repeatable other elements

### ISSUE THREAD

**Issue by izzygld** [Rhyzz/repeatable-fields#25]
Do i have to use a table for the repeatable t owork.
Would a bootstrap grid work too?
i.e. col-md-6..

**Comment by naifamoodi** [comment]
Hi,

It doesn't really matter what you use as long as there is a parent element, a wrapper element, and a container element. The container element will hold the repeating rows.

So even the following would work:

<div class="repeat">
	<div class="wrapper">
		<div class="container">
			<div class="template row">
				<input type="text" name="an-input-field[{{row-count-placeholder}}]" />
			</div>
		</div>
	</div>
</div>

The demo here http://www.rhyzz.com/repeatable-fields.html uses Bootstrap.

Regards.
