### ISSUE TITLE
Can't call default after add function

### ISSUE THREAD

**Issue by andymb** [Rhyzz/repeatable-fields#26]
Hi, I think there's a bug in line 85 preventing my after add function calling the default.

Line 85 is `self.settings.after_add(container, new_row, self.settings.after_add);`

Shouldn't it be `self.settings.after_add(container, new_row, self.after_add);` ?

**Comment by naifamoodi** [comment]
self.settings.after_add refers to a custom function passed by the caller.

If you want to call the default function from your custom function, call it using $.fn.repeatable_fields().after_add(container, new_row)
