### ISSUE TITLE
How can I add pre-populated fields with values? As you mentioned in your examples. I'm not got this code in library file.  

### ISSUE THREAD

**Issue by ghost** [Rhyzz/repeatable-fields#27]

**Comment by naifamoodi** [comment]
Hi.

Did you check the demo here: http://www.rhyzz.com/repeatable-fields.html? It already demonstrates this.

The one with the heading "A group of fields which has two rows present by default with pre-populated values" has two pre-populated files. Just look at its source coded.

This part is actually the most easiest.

**Comment by naifamoodi** [comment]
Here is the code in concern:

&lt;tr class=&quot;row&quot;&gt;
&lt;td width=&quot;40%&quot;&gt;
&lt;span class=&quot;move btn btn-info&quot;&gt;&amp;#x2195&lt;/span&gt;
&lt;span class=&quot;move-up btn btn-info&quot;&gt;&amp;#x2191&lt;/span&gt;
&lt;input type=&quot;text&quot; class=&quot;move-steps&quot; size=&quot;1&quot; value=&quot;1&quot; /&gt;
&lt;span class=&quot;move-down btn btn-info&quot;&gt;&amp;#x2193&lt;/span&gt;
&lt;/td&gt;
&lt;td width=&quot;80%&quot;&gt;
&lt;dl&gt;
&lt;dt&gt;URL&lt;/dt&gt;
&lt;dd&gt;&lt;input type=&quot;text&quot; name=&quot;grouped-entry[0][url]&quot; class=&quot;form-control&quot; value=&quot;http://www.rhyzz.com&quot; /&gt;&lt;/dd&gt;
&lt;dt&gt;Title&lt;/dt&gt;
&lt;dd&gt;&lt;input type=&quot;text&quot; name=&quot;grouped-entry[0][title]&quot; class=&quot;form-control&quot; value=&quot;Rhyzz&quot; /&gt;&lt;/dd&gt;
&lt;dt&gt;Image&lt;/dt&gt;
&lt;dd&gt;&lt;input type=&quot;text&quot; name=&quot;grouped-entry[0][image]&quot; class=&quot;form-control&quot; value=&quot;http://www.rhyzz.com/images/rhyzz.png&quot; /&gt;&lt;/dd&gt;
&lt;/dl&gt;
&lt;/td&gt;
&lt;td width=&quot;10%&quot;&gt;&lt;span class=&quot;remove btn btn-danger&quot;&gt;Remove&lt;/span&gt;&lt;/td&gt;
&lt;/tr&gt;

Notice the 0 there. This needs to be changed for all pre-populated rows. So for the first row it will be 0, 1 for the second, 2 for the third, and so on.

**Comment by ranjitredekar** [comment]
Thanks for your response.
I checked your pre-populated example but I following scenario
I have a new form and created three fields using repeatable fields enter respective values and save the form.
Next, I'm trying to edit the form then how can I get the same repeatable fields with values using repeatable fields library.  I have gone through your library but there is no any condition or settings to check if data available then pre-populated xyz fields.

**Comment by naifamoodi** [comment]
If you are referring to saved data then you'll need to use the backend language for this such as PHP.

Lets say I have an item in the database called "names".

Using the backend language, I first fetch this item and see if it has any values (i.e. names). Then I set up the HTML for this and render all names to the frontend. Now from the frontend, new values can be added, existing values can be edited or deleted and then saved again to the database.

**Comment by ranjitredekar** [comment]
I have used PHP for backend and save the data into the MySql and it successfully returns the saved data.
Maybe I need to override the **after_add** function which sets my fields values.

**Comment by naifamoodi** [comment]
No you don't. Have you set up the repeatable-fields plugin correctly?

Can I see a snippet of your code?
