### ISSUE TITLE
row-count-placeholder not incrementing when using after_add

### ISSUE THREAD

**Issue by someuserb** [Rhyzz/repeatable-fields#29]
When using after_add, repeated elements in browser have the same ID with row-count-placeholder variable showing as plain text instead of a value.

If I get rid of after_add (which is just a simple alert function), then row-count-placeholder is an integer again in repeated elements.

**Comment by naifamoodi** [comment]
Please show me your code. Both the HTML and the JS.
________________________________

**Comment by someuserb** [comment]
Hi! Using the example minimal code:

<html>
<head>
<script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js" integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU=" crossorigin="anonymous"></script>
<script src="http://www.rhyzz.com/repeatable-fields/js/repeatable-fields.js?version=1.5.0"></script>
<script type="text/javascript">

function testme() {
    alert("test");
}

jQuery(function() {
	jQuery('.repeat').each(function() {
		jQuery(this).repeatable_fields({
            after_add: self.testme,
		});
	});
});
</script>
</head>
<body>
<div class="repeat">
	<table class="wrapper" width="100%">
		<thead>
			<tr>
				<td width="10%" colspan="4"><span class="add">Add</span></td>
			</tr>
		</thead>
		<tbody class="container">
		<tr class="template row">
			<td width="10%">
				<span class="move">Move Row</span>
				<span class="move-up">Move Up</span>
				<input type="text" class="move-steps" value="1" />
				<span class="move-down">Move Down</span>
			</td>

			<td width="10%">An Input Field</td>

			<td width="70%">
				<input type="text" name="an-input-field[{{row-count-placeholder}}]" />
			</td>

			<td width="10%"><span class="remove">Remove</span></td>
		</tr>
		</tbody>
	</table>
</div>
</body>
</html>

**Comment by naifamoodi** [comment]
The after_add function is responsible for swapping the value of row-count-placeholder. If you assign a custom function there, then the original after_add function will never be called. You will have to manually call it. You can do it like this:

https://pastebin.com/6qqj4a1U

See how I modified your testme function and then call the after_add function explicitly.

**Comment by someuserb** [comment]
And if I was to change the row_count_placeholder to a unique value, how would I pass that change to the after_add function in my unique function?

**Comment by naifamoodi** [comment]
You should change the row_count_placeholder: '{{row-count-placeholder}}' argument when calling the repeatable_fields jQuery function. Example:

after_add: testme,
row_count_placeholder: 'your-custom-value',


________________________________
