### ISSUE TITLE
Remove any row but the last, then add a new row, this produces two rows with the same index

### ISSUE THREAD

**Issue by schodet** [Rhyzz/repeatable-fields#5]
How to reproduce on the demo page, first form:
 - set the first location to A
 - add a new location B
 - remove the first location A
 - add a new location C
 - submit the form

You can see in the result that location B is dropped as it used the same index as location C.

**Comment by naifamoodi** [comment]
schodet,

Thanks for reporting this.

Please have a look at the demo again: http://www.rhyzz.com/repeatable-fields/index.html

Make sure you do a forced refresh. Does the problem persist now?

I have made changes to the script here: http://www.rhyzz.com/repeatable-fields/js/repeatable-fields.js

Will upload the changes to GitHub once I am certain the problem is fixed.

Regards.

**Comment by schodet** [comment]
Thanks for your fast reply!

I can still reproduce the problem with several methods:

 - set location to A,
 - add location B,
 - add location C,
 - move location C before B,
 - add location D,
 - submit, C is gone.
 
Other method with "A group of fields which has two rows present by default with pre-populated values":

 - remove first item (title: Rhyzz)
 - add a new item
 - submit, second item is gone, and there is an empty first item.

Regards,

Nicolas.

**Comment by naifamoodi** [comment]
Thanks for testing this further. Please try again now and see if you find a method that fails.

Regards.

**Comment by schodet** [comment]
This looks OK.

Would it be simpler to store the row count in the container instead of in every rows?

**Comment by naifamoodi** [comment]
schodet,

I'll look into refactoring this plugin and see if handling it like that instead would be more efficient or not.

**Comment by naifamoodi** [comment]
I am done refactoring it. The version here does this using the method you suggested: http://www.rhyzz.com/repeatable-fields/js/repeatable-fields.js

Please try it out and see if everything seems to be in order?

Regards.

**Comment by schodet** [comment]
I think it's working right.

Thanks!
