### ISSUE TITLE
Sorting doesn't reindex

### ISSUE THREAD

**Issue by daylightstudio** [Rhyzz/repeatable-fields#8]
When sorting the rows, it doesn't appear to reindex them correct?

**Comment by naifamoodi** [comment]
Hi,

The plugin doesn't do any re-indexing. Take this demo for example: http://www.rhyzz.com/repeatable-fields.html

If you have four locations viz. A, B, C and D, their index will be 0, 1, 2 and 3 respectively. If you move D between B and C, it's index will still be 3 while the index of C will remain 2. But when you submit the form, the order in which they'll be received would be A, B, D and C.

So even though the indexes don't change, i.e. they aren't re-indexed, the order in which they are submitted will be preserved. You can try the demo.

**Comment by daylightstudio** [comment]
OK. Thanks for the response.
